-- EDU ClassRepo - PostgreSQL Database Schema
-- Run this in pgAdmin or psql

-- Create Database (run separately if needed)
-- CREATE DATABASE edu_classrepo;

-- Connect to database first, then run below:

-- ============ TABLES ============

-- Users Table
CREATE TABLE IF NOT EXISTS users (
    id SERIAL PRIMARY KEY,
    student_id VARCHAR(50) NOT NULL,
    name VARCHAR(100) NOT NULL,
    email VARCHAR(100) UNIQUE NOT NULL,
    password VARCHAR(255) NOT NULL,
    department VARCHAR(50),
    gender VARCHAR(10),
    semester VARCHAR(10),
    role VARCHAR(20) DEFAULT 'student',
    is_verified BOOLEAN DEFAULT FALSE,      -- New Column
    verification_token VARCHAR(255),        -- New Column
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Courses Table
CREATE TABLE IF NOT EXISTS courses (
    id SERIAL PRIMARY KEY,
    code VARCHAR(20) NOT NULL,
    title VARCHAR(200) NOT NULL,
    department VARCHAR(50) NOT NULL,
    instructor VARCHAR(100) DEFAULT 'TBA',
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Enrollments Table
CREATE TABLE IF NOT EXISTS enrollments (
    id SERIAL PRIMARY KEY,
    user_id INTEGER REFERENCES users(id) ON DELETE CASCADE,
    course_id INTEGER REFERENCES courses(id) ON DELETE CASCADE,
    enrolled_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UNIQUE(user_id, course_id)
);

-- Files Table
CREATE TABLE IF NOT EXISTS files (
    id SERIAL PRIMARY KEY,
    course_id INTEGER REFERENCES courses(id) ON DELETE CASCADE,
    file_name VARCHAR(255) NOT NULL,
    file_path VARCHAR(500) NOT NULL,
    file_size INTEGER,
    uploaded_by INTEGER REFERENCES users(id) ON DELETE CASCADE,
    status VARCHAR(20) DEFAULT 'pending',
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- ============ DEFAULT ADMIN ============
-- Password: admin123 (bcrypt hash)
INSERT INTO users (student_id, name, email, password, department, role) VALUES
('ADM-001', 'Admin', 'admin@eastdelta.edu.bd', '$2b$10$rICGc.pzZ3qXTzPxLxvSXOqZMlnwRLlTQHKXFqXXOEJpF5jJKQYwu', 'Admin', 'admin', true);

-- ============ ALL COURSES ============

-- CSE Department
INSERT INTO courses (code, title, department) VALUES
('CSE 111', 'Computer Fundamentals and Programming Basics', 'CSE'),
('CSE 112', 'Computer Fundamentals and Programming Basics Lab', 'CSE'),
('CSE 113', 'Structured Programming Language', 'CSE'),
('CSE 114', 'Structured Programming Language Lab', 'CSE'),
('CSE 115', 'Discrete Mathematics', 'CSE'),
('CSE 123', 'Object Oriented Programming Language', 'CSE'),
('CSE 124', 'Object Oriented Programming Language Lab', 'CSE'),
('CSE 211', 'Data Structure', 'CSE'),
('CSE 212', 'Data Structure Lab', 'CSE'),
('CSE 215', 'Digital Logic Design', 'CSE'),
('CSE 216', 'Digital Logic Design Lab', 'CSE'),
('CSE 221', 'Algorithms', 'CSE'),
('CSE 222', 'Algorithms Lab', 'CSE'),
('CSE 225', 'Database Management System', 'CSE'),
('CSE 226', 'Database Management System Lab', 'CSE'),
('CSE 242', 'Web Development', 'CSE'),
('CSE 301', 'Data Warehousing and Mining', 'CSE'),
('CSE 303', 'Introduction to Bioinformatics', 'CSE'),
('CSE 307', 'Mobile Computing and Applications', 'CSE'),
('CSE 309', 'Distributed Systems', 'CSE'),
('CSE 311', 'Operating System', 'CSE'),
('CSE 312', 'Operating System Lab', 'CSE'),
('CSE 313', 'Data Communication', 'CSE'),
('CSE 315', 'Microprocessor and Interfacing', 'CSE'),
('CSE 316', 'Microprocessor and Interfacing Lab', 'CSE'),
('CSE 317', 'Computer Organization and Architecture', 'CSE'),
('CSE 319', 'Compiler Design', 'CSE'),
('CSE 320', 'Compiler Design Lab', 'CSE'),
('CSE 321', 'Computer Graphics', 'CSE'),
('CSE 322', 'Computer Graphics Lab', 'CSE'),
('CSE 325', 'Computer Networks', 'CSE'),
('CSE 326', 'Computer Networks Lab', 'CSE'),
('CSE 327', 'Artificial Intelligence', 'CSE'),
('CSE 328', 'Artificial Intelligence Lab', 'CSE'),
('CSE 337', 'Multimedia Theory', 'CSE'),
('CSE 342', 'IoT Based Project Development', 'CSE'),
('CSE 400', 'Project / Thesis', 'CSE'),
('CSE 411', 'Software Engineering', 'CSE'),
('CSE 429', 'Software Project Management', 'CSE'),
('CSE 435', 'Pattern Recognition', 'CSE'),
('CSE 439', 'Digital Image Processing', 'CSE'),
('CSE 443', 'Neural Network and Fuzzy Systems', 'CSE'),
('CSE 455', 'Business Process Reengineering', 'CSE'),
('CSE 457', 'Cyber Security', 'CSE'),
('CSE 459', 'Network Security', 'CSE'),
('CSE 463', 'Machine Learning for Big Data Analytics', 'CSE'),
('CSE 464', 'Python Based Project Development', 'CSE'),
('CSE 466', 'Mobile App Development', 'CSE');

-- EEE Department
INSERT INTO courses (code, title, department) VALUES
('EEE 101', 'Electrical Circuits-I', 'EEE'),
('EEE 102', 'Electrical Circuits-I Lab', 'EEE'),
('EEE 103', 'Electrical Circuits-II', 'EEE'),
('EEE 104', 'Electrical Circuits-II Lab', 'EEE'),
('EEE 203', 'Electrical Machines-I', 'EEE'),
('EEE 204', 'Electrical Machines-I Lab', 'EEE'),
('EEE 205', 'Electronics-I', 'EEE'),
('EEE 206', 'Electronics-I Lab', 'EEE'),
('EEE 207', 'Electrical Machines-II', 'EEE'),
('EEE 208', 'Electrical Machines-II Lab', 'EEE'),
('EEE 217', 'Digital Electronics', 'EEE'),
('EEE 218', 'Digital Electronics Lab', 'EEE'),
('EEE 219', 'Electromagnetic Fields & Waves', 'EEE'),
('EEE 300', 'Machine Design and Simulation Lab', 'EEE'),
('EEE 301', 'Electronics-II', 'EEE'),
('EEE 302', 'Electronics-II Lab', 'EEE'),
('EEE 303', 'Signal and Systems', 'EEE'),
('EEE 306', 'Mathematical Methods in Engineering', 'EEE'),
('EEE 307', 'Science of Materials', 'EEE'),
('EEE 309', 'Digital Signal Processing', 'EEE'),
('EEE 310', 'Digital Signal Processing Lab', 'EEE'),
('EEE 311', 'Control Systems', 'EEE'),
('EEE 312', 'Control Systems Lab', 'EEE'),
('EEE 313', 'Microprocessors & Micro Controllers', 'EEE'),
('EEE 314', 'Microprocessors & Micro Controllers Lab', 'EEE'),
('EEE 317', 'Transmission & Distribution of Electrical Power', 'EEE'),
('EEE 330', 'Project (Embedded Programming)', 'EEE'),
('EEE 400', 'Project / Thesis', 'EEE'),
('EEE 401', 'Power Electronics', 'EEE'),
('EEE 402', 'Power Electronics Lab', 'EEE'),
('EEE 405', 'Fundamental Communication Engineering', 'EEE'),
('EEE 406', 'Fundamental Communication Engineering Lab', 'EEE'),
('EEE 407', 'Semiconductor Devices', 'EEE'),
('EEE 409', 'VLSI', 'EEE'),
('EEE 410', 'VLSI Lab', 'EEE'),
('EEE 411', 'Microwave Engineering', 'EEE'),
('EEE 412', 'Microwave Engineering Lab', 'EEE'),
('EEE 431', 'Cellular Mobile Communication', 'EEE'),
('EEE 433', 'Optical Fiber Communication', 'EEE'),
('EEE 435', 'Digital Communication', 'EEE'),
('EEE 436', 'Digital Communication Lab', 'EEE'),
('EEE 437', 'Wireless Communication', 'EEE'),
('EEE 438', 'Wireless Communication Lab', 'EEE'),
('EEE 439', 'Random Signal Processing', 'EEE'),
('EEE 441', 'Telecommunication Engineering', 'EEE'),
('EEE 443', 'Data Communication & Computer Networks', 'EEE'),
('EEE 445', 'Biomedical Instrumentation', 'EEE'),
('EEE 447', 'Telecommunication Switching', 'EEE'),
('EEE 451', 'Power System Analysis', 'EEE'),
('EEE 452', 'Power System Analysis Lab', 'EEE'),
('EEE 491', 'Multimedia Communications', 'EEE'),
('EEE 493', 'Internet of Things', 'EEE'),
('EEE 495', 'Internet Security and Networking', 'EEE');

-- BBA Department
INSERT INTO courses (code, title, department) VALUES
('ACT 201', 'Financial Accounting', 'BBA'),
('ACT 301', 'Management Accounting', 'BBA'),
('ACT 302', 'Audit & Taxation', 'BBA'),
('ACT 401', 'Intermediate Accounting', 'BBA'),
('ACT 402', 'Advanced Financial Accounting', 'BBA'),
('ACT 403', 'Advanced Auditing and Assurance', 'BBA'),
('ACT 404', 'Income Tax Accounting', 'BBA'),
('ACT 405', 'Cost Accounting', 'BBA'),
('ACT 406', 'Advanced Cost Accounting', 'BBA'),
('ACT 407', 'Corporate Tax, VAT and Customs', 'BBA'),
('ACT 408', 'Accounting Information System', 'BBA'),
('BUS 101', 'Introduction to Business', 'BBA'),
('BUS 301', 'Legal Environment of Business', 'BBA'),
('BUS 350', 'Business Analytics', 'BBA'),
('BUS 360', 'Leading Innovation', 'BBA'),
('BUS 430', 'Business Research Method', 'BBA'),
('FIN 201', 'Managerial Finance', 'BBA'),
('FIN 302', 'Banking & Insurance Management', 'BBA'),
('FIN 401', 'Working Capital Management', 'BBA'),
('FIN 402', 'Money and Capital Market', 'BBA'),
('FIN 404', 'Investment Analysis and Portfolio Management', 'BBA'),
('FIN 405', 'Corporate Finance', 'BBA'),
('FIN 406', 'Advanced Business Finance', 'BBA'),
('FIN 408', 'International Financial Management', 'BBA'),
('FIN 409', 'Management of Financial Institutions', 'BBA'),
('FIN 410', 'Risk and Insurance Management', 'BBA'),
('FIN 412', 'Public Finance', 'BBA'),
('FIN 413', 'Financial Statement Analysis', 'BBA'),
('FIN 415', 'Sustainable Finance', 'BBA'),
('HRM 301', 'Human Resources Management', 'BBA'),
('HRM 401', 'Labor Economics', 'BBA'),
('HRM 402', 'Human Resource Development', 'BBA'),
('HRM 404', 'Safety, Health and Environment Management', 'BBA'),
('HRM 405', 'Industrial Relations', 'BBA'),
('HRM 408', 'Human Resource Information Systems', 'BBA'),
('HRM 409', 'Industrial Psychology', 'BBA'),
('HRM 410', 'Compensation Management', 'BBA'),
('HRM 412', 'Recruitment and Selection', 'BBA'),
('HRM 413', 'Strategic Human Resource Management', 'BBA'),
('HRM 414', 'People Analytics', 'BBA'),
('MAT 202', 'Mathematics for Business', 'BBA'),
('MGT 201', 'Principles of Management', 'BBA'),
('MGT 301', 'Organizational Behavior', 'BBA'),
('MGT 302', 'Labor Law', 'BBA'),
('MGT 401', 'Management Science', 'BBA'),
('MGT 402', 'Total Quality Management', 'BBA'),
('MGT 403', 'Change Management', 'BBA'),
('MGT 404', 'Social Business', 'BBA'),
('MGT 405', 'Supply Chain and Logistics Management', 'BBA'),
('MGT 406', 'Leadership and Conflict Management', 'BBA'),
('MGT 407', 'Group Behavior and Organizational Design', 'BBA'),
('MGT 412', 'Project Management', 'BBA'),
('MGT 450', 'Strategic Management', 'BBA'),
('MIS 301', 'Management Information System', 'BBA'),
('MKT 201', 'Principles of Marketing', 'BBA'),
('MKT 301', 'Marketing Management', 'BBA'),
('MKT 401', 'Consumer Behavior', 'BBA'),
('MKT 402', 'Integrated Marketing Communications', 'BBA'),
('MKT 403', 'Service Marketing', 'BBA'),
('MKT 404', 'Marketing Research', 'BBA'),
('MKT 405', 'Trade Marketing and Distribution Management', 'BBA'),
('MKT 406', 'International Marketing', 'BBA'),
('MKT 407', 'Product Pricing Policies', 'BBA'),
('MKT 409', 'Brand Management', 'BBA'),
('MKT 410', 'Selling and Salesmanship', 'BBA'),
('MKT 411', 'Customer Relationship Management', 'BBA'),
('MKT 413', 'Tourism Marketing and Hospitality Management', 'BBA'),
('MKT 414', 'Strategic Marketing Management', 'BBA'),
('MKT 415', 'Digital Marketing Management', 'BBA'),
('SCM 303', 'Principles of Supply Chain Management', 'BBA'),
('SCM 401', 'Strategic Supply Chain Management', 'BBA'),
('SCM 402', 'Supply Chain Planning and Control', 'BBA'),
('SCM 403', 'Material Management', 'BBA'),
('SCM 404', 'Quality Management', 'BBA'),
('SCM 405', 'Negotiating Skills and Techniques', 'BBA'),
('SCM 406', 'Sourcing Management', 'BBA'),
('SCM 407', 'Supply Chain Logistics Management', 'BBA'),
('INT 600', 'Internship/Dissertation', 'BBA');

-- English Department
INSERT INTO courses (code, title, department) VALUES
('ENG 141', 'Introduction to Literature', 'ENG'),
('ENG 142', 'Introduction to Linguistics', 'ENG'),
('ENG 158', 'Classics in Translation', 'ENG'),
('ENG 160', 'History of English Language and Literature', 'ENG'),
('ENG 208', 'Applied Linguistics', 'ENG'),
('ENG 211', 'Old and Middle English in Translation', 'ENG'),
('ENG 242', 'Elizabethan and Jacobean Drama', 'ENG'),
('ENG 245', 'Sixteenth and Seventeenth-Century Literature', 'ENG'),
('ENG 248', 'Romantic Literature', 'ENG'),
('ENG 251', 'Restoration and Eighteenth-Century Literature', 'ENG'),
('ENG 255', 'Literary Criticism', 'ENG'),
('ENG 257', 'Literary Theory', 'ENG'),
('ENG 258', 'Linguistic Theories', 'ENG'),
('ENG 281', 'Victorian Literature', 'ENG'),
('ENG 290', 'Theatre and Adaptation Studies', 'ENG'),
('ENG 315', 'American Literature: Puritanism to 19th Century', 'ENG'),
('ENG 321', 'Shakespeare', 'ENG'),
('ENG 330', 'Methodology of Language Teaching', 'ENG'),
('ENG 342', 'Modern Literature', 'ENG'),
('ENG 346', 'Twentieth-Century American Literature', 'ENG'),
('ENG 351', 'ELT Theories and Practices', 'ENG'),
('ENG 356', 'Applied Literature', 'ENG'),
('ENG 361', 'Postcolonial Literature', 'ENG'),
('ENG 370', 'Digital Humanities', 'ENG'),
('ENG 378', 'Comparative Literature', 'ENG'),
('ENG 381', 'Teaching Language through Literature', 'ENG'),
('ENG 421', 'Migration and Diaspora Studies', 'ENG'),
('ENG 428', 'Health Humanities', 'ENG'),
('ENG 434', 'Pragmatics and Discourse Analysis', 'ENG'),
('ENG 438', 'Literature and Sustainability', 'ENG'),
('ENG 459', 'Liberal Arts in the 21st Century', 'ENG'),
('ENG 464', 'Language, Literature, and Education', 'ENG'),
('ENG 471', 'Research Methodology', 'ENG'),
('ENG 472', 'BA Thesis', 'ENG');

-- Economics Department
INSERT INTO courses (code, title, department) VALUES
('ECO 101', 'Introduction to Microeconomics', 'ECO'),
('ECO 102', 'Introduction to Macroeconomics', 'ECO'),
('ECO 201', 'Intermediate Microeconomics', 'ECO'),
('ECO 202', 'Intermediate Macroeconomics', 'ECO'),
('ECO 203', 'Public Finance', 'ECO'),
('ECO 204', 'Environmental and Natural Resource Economics', 'ECO'),
('ECO 300', 'Econometrics and Statistics Lab', 'ECO'),
('ECO 301', 'Money and Banking', 'ECO'),
('ECO 302', 'History of Economic Thought', 'ECO'),
('ECO 303', 'Development Economics', 'ECO'),
('ECO 304', 'Agricultural Economics', 'ECO'),
('ECO 305', 'Socio Economic Development of Bangladesh', 'ECO'),
('ECO 306', 'Introduction to Mathematical Economics', 'ECO'),
('ECO 307', 'Introduction to Econometrics', 'ECO'),
('ECO 308', 'Monetary Economics', 'ECO'),
('ECO 311', 'International Trade', 'ECO'),
('ECO 401', 'Contemporary Issues in Global Economy', 'ECO'),
('ECO 402', 'Economics of Human Resources and Health', 'ECO'),
('ECO 403', 'Project Analysis and Evaluation', 'ECO'),
('ECO 404', 'Research Methods in Economics', 'ECO'),
('ECO 405', 'Economics of Cost Benefit Analysis', 'ECO'),
('ECO 409', 'Game Theory and Applications', 'ECO'),
('ECO 411', 'Applied Economics', 'ECO'),
('ECO 412', 'Economics of Information', 'ECO'),
('ECO 413', 'Advanced Microeconomic Theory', 'ECO'),
('ECO 414', 'Mathematical Economics', 'ECO'),
('ECO 415', 'Advanced Macroeconomic Theory', 'ECO'),
('ECO 416', 'Econometric Methods', 'ECO'),
('ECO 417', 'Special Topics in Economics', 'ECO'),
('ECO 418', 'Welfare Economics', 'ECO'),
('ECO 420', 'Political Economy of Development', 'ECO'),
('ECO 421', 'International Economic Theory', 'ECO'),
('ECO 422', 'Trade Policy Analysis', 'ECO'),
('ECO 423', 'Gender and Development', 'ECO'),
('ECO 425', 'Economic Development in South Asia', 'ECO'),
('ECO 426', 'Energy Economics and Policy', 'ECO'),
('ECO 427', 'Economic Valuation of the Environment', 'ECO'),
('ECO 428', 'Economics of Climate Change', 'ECO'),
('ECO 429', 'Environmental Policy', 'ECO'),
('ECO 431', 'Population, Environment and Development', 'ECO'),
('ECO 434', 'Natural Resources Economics', 'ECO'),
('ECO 443', 'Managerial Economics', 'ECO'),
('ECO 447', 'Health Economics', 'ECO'),
('ECO 448', 'Labour Economics', 'ECO'),
('ECO 500', 'Research Paper', 'ECO');

-- General Education (GED)
INSERT INTO courses (code, title, department) VALUES
('AA 099', 'Academic Reading and Writing', 'GED'),
('AA 150', 'Fundamentals of Quantitative Reasoning', 'GED'),
('AA 200', 'Student Development Seminars', 'GED'),
('ENG 101', 'English Fundamentals', 'GED'),
('ENG 102', 'Advanced Composition', 'GED'),
('ENG 111', 'Advanced Academic Reading and Writing', 'GED'),
('MAT 101', 'Introduction to Mathematics', 'GED'),
('MAT 105', 'Mathematics for Economics', 'GED'),
('PHY 101', 'Physics', 'GED'),
('PHY 102', 'Physics Laboratory', 'GED'),
('CHEM 201', 'Chemistry', 'GED'),
('MATH 107', 'Differential Calculus & Complex Variables', 'GED'),
('MATH 207', 'Integral Calculus & Linear Algebra', 'GED'),
('MATH 301', 'Probability & Statistics', 'GED'),
('BNG 101', 'Bangla Language and Literature', 'GED'),
('HIS 101', 'History of the Emergence of Bangladesh', 'GED'),
('PSC 100', 'Introduction to Political Science', 'GED'),
('PSY 101', 'Principles of Psychology', 'GED'),
('SOC 101', 'Introduction to Sociology', 'GED'),
('PHL 101', 'Introduction to Philosophy', 'GED'),
('ANT 101', 'Physical Anthropology', 'GED'),
('ENV 101', 'Introduction to Environmental Studies', 'GED'),
('BCH 101', 'Bangladesh Culture and Heritage', 'GED'),
('SDA 101', 'Public Speaking', 'GED'),
('IPD 400', 'Integrated Professional Development', 'GED');

-- Verify insertion
SELECT department, COUNT(*) as course_count FROM courses GROUP BY department ORDER BY department;
